### ISSUE TITLE
Added proxy support

### ISSUE THREAD

**Issue by sblfc** [JackOHara/glasto-helper#1]
Sorry removed from public as so many people using it can't be good. Also probably does not work any more as they've started not allowing access though vpns and some other non residential ips I think.

The unethical point is also correct I think. If you can code its not hard to make yourself.

**Comment by JackOHara** [comment]
Hi @sblfc that is really cool how much extra you squeezed out of it (kind of unethical but impressive lol)! It's been a few years since I wrote this initially but I have been using Puppeteer keenly since so I might get this going again for the next sale.

BTW I'm not sure if you found this but [here is a blog post](https://jackohara.com/glastonbury/) I wrote on the original project.

**Comment by StevenBendell** [comment]
Hi @sblfc 

Nice that you got it working with proxy support, your repo is no longer accessible. Would you kindly share your code with me?

Thanks

**Comment by joepaynterVF** [comment]
> Hi @sblfc
> 
> Nice that you got it working with proxy support, your repo is no longer accessible. Would you kindly share your code with me?
> 
> Thanks

Any luck with this?

**Comment by StevenBendell** [comment]
> > Hi @sblfc
> > Nice that you got it working with proxy support, your repo is no longer accessible. Would you kindly share your code with me?
> > Thanks
> 
> Any luck with this?

I didn't get a reply, I've been making my own implementation

**Comment by ghost** [comment]
Sorry, it was open, but it had quite a few downloads, so I removed it. I don't really want to help so many people bot it so easily to be honest.

**Comment by cdrapes** [comment]
Are you planning on making the repo public @StevenBendell ?

**Comment by StevenBendell** [comment]
> Are you planning on making the repo public @StevenBendell ?

I won't be making it public,  I'd maybe consider sharing to a select few people

**Comment by Samba-999** [comment]
@StevenBendell Would be interested if you are considering a limited share. Thanks.

**Comment by cdrapes** [comment]
Me too :) if you don't mind @StevenBendell ! Cheers

**Comment by tomgreeEn** [comment]
I'd be happy to contribute too @StevenBendell :) 
Peace and love✌️

**Comment by JNET012** [comment]
@StevenBendell Would love to contribute to repo if possible :) All the best mate

**Comment by lilaceri** [comment]
Hi, 

I'm trying to implement this for 2024 tickets, any chance I could see your repo's @StevenBendell or @sblfc ?

**Comment by rorymullan** [comment]
Can't you just set the proxy-server puppeteer flag on the existing implementation and run multiple instances with different proxies? Quick and nasty but it should work right?
